apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-tls-secret
spec:
  secretName: app-tls-secret
  issuerRef:
    name: letsencrypt-prod 
    kind: ClusterIssuer
  dnsNames:
    - my-nodejs-app.com  
